### ISSUE TITLE
Exclude pending approval section

### ISSUE THREAD

**Issue by paulius-p** [connorsmallman/github-jira-changelog-action#8]
Hi, thanks for making this action! Few suggestions that I'd have:
 - a possibility to exclude the `Pending Approval` section, as in my use case I'm using this for release notes and this section is not relevant.
 - sorting the release versions by project key and hiperlinking them instead ` - [projectKey](<jira link>)`

**Comment by connorsmallman** [comment]
@paulius-p I will add a flag for pending approval soon and will investigate the sorting and hyperlinking. Thanks for the suggestions!

**Comment by paulius-p** [comment]
Just to clarify for sorting I meant this section:
https://github.com/connorsmallman/github-jira-changelog-action/blob/754e660d72d69c80f9827faa7c15d14f53917e3c/index.js#L36-L39

to include something like `jira.releaseVersions.sort((a, b) => a.projectKey.localeCompare(b.projectKey))`, so that the order would be the same per changelog and not depend on the order of commits.

**Comment by paulius-p** [comment]
Solved in #12
